# Generated by Django 4.0.9 on 2024-01-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='send_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_send', models.BooleanField(default=False)),
                ('is_seen', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=50000, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('logger', models.BooleanField(default=True)),
                ('update_check', models.BooleanField(default=True)),
            ],
        ),
    ]
